fix: ignoring jetpack ability when player is in GameMode
Nova-Addons/Jetpacks pull request #1
Opened 2023-06-24 18:49 UTC by DevSrSouza

Hi folks! Small contribution for ignoring Removable of Fly when the player is with Jetpack and in GameMode Creative or Spectator.

This also disable losing chargeable or even requiring to have any energy to show particles and sound. 

There is a bunch of if statements, I know, but this was to keep the "Jetpack behavior and effects" while in Creative.

2023-06-24 19:48 UTC, NichtStudioCode requested changes
Please also reformat your code with the [xenondevs codestyle](https://github.com/xenondevs/Nova/blob/main/codestyle.xml)

2023-06-24 19:48 UTC, NichtStudioCode commented on src/main/kotlin/xyz/xenondevs/nova/jetpacks/ability/JetpackFlyAbility.kt
> +        if (energyLeft > energyPerTick || isValidGameMode().not()) {
prefer the ! operator

2023-06-24 19:48 UTC, NichtStudioCode commented on src/main/kotlin/xyz/xenondevs/nova/jetpacks/registry/Abilities.kt
> +}
This should probably be in JetpackFlyAbility if it's the same across all jetpack types

2023-06-24 19:48 UTC, NichtStudioCode commented on src/main/resources/configs/config.yml
> +ignored_game_mode:
I think this should be `ignored_game_modes`? It's also plural in code.

2023-06-25 11:00 UTC, DevSrSouza commented
> Please also reformat your code with the [xenondevs codestyle](https://github.com/xenondevs/Nova/blob/main/codestyle.xml)

I was already using it, the IntelliJ format does not change anyway on the current source code

2023-06-25 11:01 UTC, NichtStudioCode commented on src/main/kotlin/xyz/xenondevs/nova/jetpacks/ability/JetpackFlyAbility.kt
> +
🤔

2023-06-25 11:04 UTC, NichtStudioCode commented on src/main/kotlin/xyz/xenondevs/nova/jetpacks/ability/JetpackFlyAbility.kt
> +    }
That's not what I meant. It should still a top level declaration.

2023-06-25 17:28 UTC, NichtStudioCode commented
Thanks, I'll fix the remaining issues myself.

2023-06-25 17:28 UTC, merged